#!/usr/bin/env php
<?php

error_reporting(E_ALL);
ini_set('display_errors', '1');

set_error_handler(function($errno, $errstr, $errfile, $errline) {

	if ($errno & error_reporting()) {
		throw new ErrorException($errstr, $errno, 0, $errfile, $errline);
	}
	
});

require __DIR__ . '/vendor/autoload.php';

(new GitSshDeploy\Console())->execute(
	array_slice($argv, 1)
);



// use phpseclib\Crypt\RSA;
// use phpseclib\Net\SSH2;

// $key = new RSA();
// $key->loadKey(file_get_contents('private-key.txt'));

// // Domain can be an IP too
// $ssh = new SSH2('www.domain.tld');
// if (!$ssh->login('username', $key)) {
//     exit('Login Failed');
// }

// echo $ssh->exec('pwd');
// echo $ssh->exec('ls -la');