#!/usr/bin/env php
<?php

error_reporting(E_ALL);
ini_set('display_errors', '1');

set_error_handler(function($errno, $errstr, $errfile, $errline) {

	if ($errno & error_reporting()) {
		throw new ErrorException($errstr, $errno, 0, $errfile, $errline);
	}

});

require __DIR__ . '/vendor/autoload.php';



// `instanceof` does not trigger autoloading, because technically an object 
// can't be an instance of a class/interface that hasn't been loaded yet. 
// Except when `class_alias` is used. Which is the case for the following file.
// So we'll manually trigger autoloading before any other code is run.
interface_exists(JustDeploy\FilesystemInterface::class);



function require_sandboxed($___path, $___scope=[])
{
	extract($___scope);

	return require($___path);
}

(new JustDeploy\Application())->execute(
	array_slice($argv, 1),
	$_ENV
);