#!/usr/bin/env php
<?php

error_reporting(E_ALL);
ini_set('display_errors', '1');

set_error_handler(function($errno, $errstr, $errfile, $errline) {

	if ($errno & error_reporting()) {
		throw new ErrorException($errstr, $errno, 0, $errfile, $errline);
	}

});

require __DIR__ . '/vendor/autoload.php';

(new JustDeploy\Console())->execute(
	array_slice($argv, 1)
);